name: Roadmap — Comment on Merge
on: { pull_request_target: { types: [closed] } }
jobs:
  comment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: { contents: read, pull-requests: write }
    env:
      ROADMAP_ENV: dev
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci || true
      - name: Compare base vs merged
        env:
          BASE_SHA:  ${{ github.event.pull_request.base.sha }}
          MERGE_SHA: ${{ github.event.pull_request.merge_commit_sha }}
        run: node scripts/compare-roadmap.mjs > comment.md
      - name: Post PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('comment.md','utf8');
            await github.rest.issues.createComment({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              body
            });
